### ISSUE TITLE
Promising App Crashes Upon Startup

### ISSUE THREAD

**Issue by HonestAbe7** [TecCheck/FastLyrics#2]
This app does look promising. But unfortunately, the app crashes when I try to use it. I am using Android 10.

**Comment by TecCheck** [comment]
I'll have a look at this issue

**Comment by PeterKW** [comment]
This is the crash report I'm getting
```
FATAL EXCEPTION: main
Process: io.github.teccheck.fastlyrics, PID: 7017
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.teccheck.fastlyrics/io.github.teccheck.fastlyrics.MainActivity}: android.view.InflateException: Binary XML file line #15 in io.github.teccheck.fastlyrics:layout/activity_main: Binary XML file line #34 in io.github.teccheck.fastlyrics:layout/app_bar_main: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3636)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3793)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7894)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: android.view.InflateException: Binary XML file line #15 in io.github.teccheck.fastlyrics:layout/activity_main: Binary XML file line #34 in io.github.teccheck.fastlyrics:layout/app_bar_main: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #34 in io.github.teccheck.fastlyrics:layout/app_bar_main: Error inflating class fragment
Caused by: java.lang.SecurityException: Missing permission to control media.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.media.session.ISessionManager$Stub$Proxy.getSessions(ISessionManager.java:746)
	at android.media.session.MediaSessionManager.getActiveSessionsForUser(MediaSessionManager.java:264)
	at android.media.session.MediaSessionManager.getActiveSessions(MediaSessionManager.java:194)
	at io.github.teccheck.fastlyrics.api.MediaSession.getDefaultMediaSessionController(MediaSession.kt:43)
	at io.github.teccheck.fastlyrics.api.MediaSession.registerSongMetaListener(MediaSession.kt:29)
	at io.github.teccheck.fastlyrics.ui.fastlyrics.FastLyricsViewModel.setupSongMetaListener(FastLyricsViewModel.kt:44)
	at io.github.teccheck.fastlyrics.ui.fastlyrics.FastLyricsFragment.onCreateView(FastLyricsFragment.kt:104)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
	at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:394)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:260)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at io.github.teccheck.fastlyrics.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:53)
	at io.github.teccheck.fastlyrics.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:47)
	at io.github.teccheck.fastlyrics.MainActivity.onCreate(MainActivity.kt:29)
	at android.app.Activity.performCreate(Activity.java:8050)
	at android.app.Activity.performCreate(Activity.java:8030)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3609)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3793)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7894)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.media.MediaSessionService.enforceMediaPermissions(MediaSessionService.java:605)
	at com.android.server.media.MediaSessionService.access$4100(MediaSessionService.java:104)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.verifySessionsRequest(MediaSessionService.java:2094)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.getSessions(MediaSessionService.java:1225)
	at android.media.session.ISessionManager$Stub.onTransact(ISessionManager.java:324)

```

**Comment by TecCheck** [comment]
The new release is now up
