### ISSUE TITLE
App crashes when opening app

### ISSUE THREAD

**Issue by klaurence** [TecCheck/FastLyrics#26]
### Description

FastLyrics crashes when I open the app.

This is possibly related to #21, but the errors are different to one another.

<details>
<summary>Crash log</summary>

```
FATAL EXCEPTION: main
Process: io.github.teccheck.fastlyrics, PID: 6256
java.lang.NoSuchMethodError: No virtual method isActive()Z in class Landroid/media/session/PlaybackState; or its super classes (declaration of 'android.media.session.PlaybackState' appears in /system/framework/framework.jar!classes2.dex)
	at io.github.teccheck.fastlyrics.api.MediaSession$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at io.github.teccheck.fastlyrics.api.MediaSession.init(MediaSession.kt:48)
	at io.github.teccheck.fastlyrics.FastLyricsApp.onCreate(FastLyricsApp.kt:12)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6866)
	at android.app.ActivityThread.access$1600(ActivityThread.java:242)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```
</details>

### Environment information

- Android: 10
- App version: 0.5.1 (6)
- App downloaded from: GitHub

**Comment by TecCheck** [comment]
Thanks for the bugreport. I think I know why this bug occurs. I'll try to fix it soon

**Comment by TecCheck** [comment]
I've published a new release (0.5.2) on here on Github. Does this fix the problem?

**Comment by klaurence** [comment]
It does. Thank you!
